{
  "uid" : "7f4b9646cd252861",
  "name" : "test_app_login_0_13812345678",
  "fullName" : "scripts.test05_app_login.TestAppLogin#test_app_login_0_13812345678",
  "historyId" : "8d2c2f81b1089b9324ef352229997121",
  "time" : {
    "start" : 1600851883710,
    "stop" : 1600851897820,
    "duration" : 14110
  },
  "status" : "passed",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ {
    "name" : "_UnitTestCase__pytest_class_setup",
    "time" : {
      "start" : 1600851864767,
      "stop" : 1600851883709,
      "duration" : 18942
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "testStage" : {
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "6b28dca122e861ad",
      "name" : "log",
      "source" : "6b28dca122e861ad.txt",
      "type" : "text/plain",
      "size" : 2112
    } ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 1,
    "hasContent" : true,
    "stepsCount" : 0
  },
  "afterStages" : [ {
    "name" : "_UnitTestCase__pytest_class_setup::0",
    "time" : {
      "start" : 1600851897820,
      "stop" : 1600851899696,
      "duration" : 1876
    },
    "status" : "passed",
    "steps" : [ ],
    "attachments" : [ ],
    "parameters" : [ ],
    "shouldDisplayMessage" : false,
    "attachmentsCount" : 0,
    "hasContent" : false,
    "stepsCount" : 0
  } ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "scripts"
  }, {
    "name" : "suite",
    "value" : "test05_app_login"
  }, {
    "name" : "subSuite",
    "value" : "TestAppLogin"
  }, {
    "name" : "host",
    "value" : "DESKTOP-DGCGN8L"
  }, {
    "name" : "thread",
    "value" : "11956-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "scripts.test05_app_login"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ {
      "uid" : "e94e01445072673f",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF487A19D0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1600851375537,
        "stop" : 1600851375537,
        "duration" : 0
      }
    }, {
      "uid" : "1ef29da56cf3a3a6",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF48BA6FA0>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1600851365380,
        "stop" : 1600851365380,
        "duration" : 0
      }
    }, {
      "uid" : "e76ac139b0b0b49a",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x000001CF47DC7610>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1600851355091,
        "stop" : 1600851355091,
        "duration" : 0
      }
    }, {
      "uid" : "aa57e0a35b3c5ecd",
      "status" : "broken",
      "statusDetails" : "urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=4723): Max retries exceeded with url: /wd/hub/session (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000026165617D30>: Failed to establish a new connection: [WinError 10061] 由于目标计算机积极拒绝，无法连接。'))",
      "time" : {
        "start" : 1600768386872,
        "stop" : 1600768386872,
        "duration" : 0
      }
    } ],
    "categories" : [ ],
    "tags" : [ ]
  },
  "source" : "7f4b9646cd252861.json",
  "parameterValues" : [ ]
}